# Generated by Django 4.1.7 on 2023-04-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True, verbose_name='tg id')),
                ('tg_chat_id', models.BigIntegerField(verbose_name='tg chat id')),
                ('username', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='tg username')),
                ('verification_code', models.CharField(max_length=12, verbose_name='Код подтверждения')),
            ],
            options={
                'verbose_name': 'Telegram пользователь',
                'verbose_name_plural': 'Telegram пользователи',
            },
        ),
    ]
